name: livit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  country_picker_pro: ^0.0.4
  pinput: ^5.0.0
  google_sign_in_dartio: ^0.3.0
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  blobs: ^2.0.0
  image_size_getter: ^2.1.3
  flutter_animate: ^4.5.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^5.3.0
  share_plus: ^10.0.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  cloud_functions: ^5.1.3
  platform_maps_flutter: ^1.0.2
  csc_picker: ^0.2.7
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  video_thumbnail: ^0.5.3
  video_editor: ^3.0.0
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  fraction: ^5.0.3
  video_player: ^2.9.2
  inview_notifier_list: ^3.0.0
  device_info_plus: ^11.2.0
  flutter_test:
    sdk: flutter
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  firebase_app_check: ^0.3.2
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.4.0
  intl: ^0.20.2
  apple_maps_flutter: ^1.4.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: HelveticaNowDisplay
      fonts:
        - asset: assets/fonts/HelveticaNowDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNowDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNowDisplay-Bold.ttf
          weight: 700

  assets:
      - assets/

      - assets/data/departments_cities.csv

      - assets/logos/google-logo.svg
      - assets/logos/google-logo.png
      - assets/logos/apple-logo-black.svg
      - assets/logos/apple-logo-white.svg

      - assets/icons/arrow-back.svg
      - assets/icons/binoculars.svg
      - assets/icons/home.svg
      - assets/icons/magic-wand.svg
      - assets/icons/profile.svg
      - assets/icons/friends.svg
      - assets/icons/tickets.svg
      - assets/icons/line.svg

      - assets/images/dots.svg
      - assets/images/dots.png
      - assets/images/dots-blurred.png
      - assets/images/blobs/blob1.svg
      - assets/images/blobs/blob2.svg
      - assets/images/blobs/blob3.svg
      - assets/images/blobs/blob4.svg
      - assets/images/blobs/blob5.svg
      - assets/images/blobs/blob1.png
      - assets/images/blobs/blob2.png
      - assets/images/blobs/blob3.png
      - assets/images/blobs/blob4.png
      - assets/images/blobs/blob5.png

      # Remove this after testing
      - assets/test/test_video_afterlife.mp4
      - assets/test/test_cover_afterlife.png